version: "3"

services:
  app:
    build:
      context: ./
      args:
        - NODE_ENV=${NODE_ENV}
    container_name: devops-app
    environment:
      API_KEY_DEV: ${API_KEY_DEV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: database:5432
      POSTGRES_DB: ${POSTGRES_DB}
      PG_LOGGING: ${PG_LOGGING}
    ports:
      - 8080:3000
    command: node dist/index.js
    depends_on:
      - migration
      - database

  database:
    image: postgres:15.2
    container_name: devops-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  migration:
    image: flyway/flyway:9.15.1
    container_name: devops-database-migration
    environment:
      FLYWAY_URL: jdbc:postgresql://database/${POSTGRES_DB}
      FLYWAY_USER: ${POSTGRES_USER}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD}
    command:
      - -connectRetries=60
      - migrate
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - database
