name: Build, Push & Deploy

on:
  push:
    branches: [master]
    # Publish semver tags as releases.
    tags: [v*.*.*]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup required Node version
      # https://github.com/actions/setup-node
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install modules
        run: yarn install --frozen-lockfiles

  test:
    needs: [build-app]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup required Node version
      # https://github.com/actions/setup-node
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

  build-and-push:
    needs: [build-app, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Set up Docker Buildx with docker-container drive
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.4.1

      # Extract metadata (tags, labels) from Git(Hub) for images
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      # Note: Permissions needed to be fixed. See https://github.com/docker/build-push-action/issues/463#issuecomment-924995909
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-staging:
    needs: [build-and-push]
    runs-on: self-hosted
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Test kubectl natively
        run: kubectl get pods

      # # Setup kubectl for local k8s cluster
      # # https://github.com/steebchen/kubectl
      # - name: Test Kubectl
      #   uses: steebchen/kubectl@v2.1.1
      #   with:
      #     config: ${{ secrets.MINIKUBE_KUBE_CONFIG }}
      #     command: kubectl get pods
