name: Build-App & Test

on:
  push:
    branches-ignore: [master]
  pull_request:
    types: [reopened]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-app:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup required Node version
      # https://github.com/actions/setup-node
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install modules
        run: yarn install --frozen-lockfiles

  test:
    needs: [build-app]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup required Node version
      # https://github.com/actions/setup-node
      - name: Setup Node version
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
